### ISSUE TITLE
Does it work with iSO? 

### ISSUE THREAD

**Issue by recitfad** [poeticAndroid/a-game#37]
It doesn't seem to work with IOS  (iPhone)

**Comment by poeticAndroid** [comment]
Could you describe what issues you run into with iOS? Does it work with stock [A-Frame](https://aframe.io)?

I don't have an iOS device myself, so I can't test it.. But iOS is known to have limited to no support for WebXR..
https://aframe.io/docs/1.2.0/introduction/vr-headsets-and-webvr-browsers.html#which-browsers-does-a-frame-support

**Comment by recitfad** [comment]
It work on computer, Chromebook  android, an some ISO devices. But It seen never finish to load on IPhone 12. This is the page I tried to load. https://moodledev5.recitfad.com/course/format/vrtopics/vr.php?courseid=207&section=2 
and this is wath appening on iPhon
![agame](https://user-images.githubusercontent.com/49538894/144880912-6d4448d6-226b-49d4-9c15-f50e823826e3.png)
e.

**Comment by poeticAndroid** [comment]
Try to remove the script to a-game, so that only A-Frame is loaded..
if you have the same problem, it might be an issue with [A-Frame](https://github.com/aframevr/aframe) or that iOS simply doesn't support it..

**Comment by recitfad** [comment]
II remove the a-game script and the scene had load. Waht can I do to help to fix this issue?
I will check, Probably, our serveur is not avalable out of Canada.

**Comment by poeticAndroid** [comment]
So the scene loads fine without a-game?
and with a-game it loads fine on all devices except iPhone 12..?

if that's the case, I don't think there is much I can do, since I don't own any Apple devices to test on..

**Comment by recitfad** [comment]
I did the up-date to ISO 15.3 yesterday and it works now.

**Comment by poeticAndroid** [comment]
sounds good.. I'll close the issue
