### ISSUE TITLE
How to set the laser-controls ?

### ISSUE THREAD

**Issue by recitfad** [poeticAndroid/a-game#38]
Hi again,
I tried to setup the laser-controls for the oculus rift.  I'm sure doing something wrong. The scene freeze and didn't work.
Any idea?

**Comment by poeticAndroid** [comment]
Hey! it seems the modifications I made to a-frame's `raycaster` component wasn't entirely backwards compatible..
It should be fixed now in version 0.42.0

**Comment by recitfad** [comment]
Thank you. It works !

**Comment by poeticAndroid** [comment]
awesome!

closing issue
